dist: trusty
language: node_js
node_js:
- '8'

npm:
- '5'

cache:
  directories:
  - node_modules

script:
- npm run build
- npm run test-ci

after_success:
- npm run coverage
- npm run release

deploy:
- provider: script
  on:
    branch: master
  script: npm run vendor && npm run build-storybook && cp -r ./public/assets ./.out/
  skip_cleanup: true
- provider: surge
  on:
    branch: master
  project: ./.out/
  domain: react-ui-components.surge.sh
  skip_cleanup: true
